import type { HeroDefinition, HeroId } from "../domain/types";

export const HEROES: Readonly<Record<HeroId, HeroDefinition>> = {
  guardian: {
    id: "guardian",
    name: "曜盾·岚",
    role: "block",
    cost: 4,
    attack: 34,
    attackIntervalMs: 1050,
    rangeColumns: 1,
    blockCapacity: 2,
    evolvedRule: "wall-aura",
    color: "#f4c95d",
  },
  ranger: {
    id: "ranger",
    name: "逐风·翎",
    role: "speed-counter",
    cost: 3,
    attack: 28,
    attackIntervalMs: 620,
    rangeColumns: 4,
    blockCapacity: 0,
    evolvedRule: "lane-pierce",
    color: "#74e5c1",
  },
  mage: {
    id: "mage",
    name: "紫电·澪",
    role: "armor-break",
    cost: 5,
    attack: 58,
    attackIntervalMs: 1450,
    rangeColumns: 3,
    blockCapacity: 0,
    evolvedRule: "cross-lane-chain",
    color: "#c18cff",
  },
  engineer: {
    id: "engineer",
    name: "机巧·洛",
    role: "zone-control",
    cost: 4,
    attack: 22,
    attackIntervalMs: 760,
    rangeColumns: 3,
    blockCapacity: 1,
    evolvedRule: "portable-turret",
    color: "#ff9868",
  },
  priest: {
    id: "priest",
    name: "圣契·伊",
    role: "support",
    cost: 3,
    attack: 20,
    attackIntervalMs: 900,
    rangeColumns: 2,
    blockCapacity: 1,
    evolvedRule: "overflow-shield",
    color: "#9cc8ff",
  },
};
